SELECT @@SERVICENAME, HOST_NAME(), GETDATE()

SELECT TOP (3)
    CODVJG,
    DESVJG,
    FECPUBVJG,
    MULTI,
    CODCAT,
    CODFAB,
    STATUS
FROM BD_T3_T3FL.[dbo].[T3FL_VIDEOJUEGO]
ORDER BY FECPUBVJG ASC

USE BD_T3_T3FL

-- PREGUNTA 1
-- A

CREATE PROCEDURE SP_VIDEOJUEGO_INSERT (
    @p_CODVJG CHAR(5),
    @p_DESVJG VARCHAR(100),
    @p_FECPUBVJG DATE,
    @p_MULTI CHAR(1),
    @p_CODCAT INT,
    @p_CODFAB CHAR(3),
    @p_STATUS CHAR(1)
)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM T3FL_VIDEOJUEGO WHERE CODVJG = @p_CODVJG)
    BEGIN
        RAISERROR ('Error: Ya existe código.', 16, 1)
        RETURN
    END

    IF NOT EXISTS (SELECT 1 FROM T3FL_CATEGORIA WHERE CODCAT = @p_CODCAT)
    BEGIN
        RAISERROR ('Error: Categoría de producto no existe.', 16, 1)
        RETURN
    END

    -- c.	Que valide los check constraints propios de la tabla.
    IF NOT (@p_FECPUBVJG > '1998-01-01')
    BEGIN
        RAISERROR ('Error: Fecha de publicación debe ser posterior a 1998-01-01.', 16, 1)
        RETURN
    END

    IF NOT (@p_MULTI IN ('S', 'N'))
    BEGIN
        RAISERROR ('Error: Valor para columna MULTI debe ser ''S'' o ''N''.', 16, 1)
        RETURN
    END

    IF NOT (@p_STATUS IN ('D', 'R'))
    BEGIN
        RAISERROR ('Error: Valor de columna STATUS debe ser ''D'' o ''R''.', 16, 1)
        RETURN
    END

    BEGIN TRY
        INSERT INTO T3FL_VIDEOJUEGO (CODVJG, DESVJG, FECPUBVJG, MULTI, CODCAT, CODFAB, STATUS)
        VALUES (@p_CODVJG, @p_DESVJG, @p_FECPUBVJG, @p_MULTI, @p_CODCAT, @p_CODFAB, @p_STATUS);      
     END TRY
    BEGIN CATCH
        RETURN
    END CATCH
END

SELECT * FROM sys.check_constraints
select * from T3FL_VIDEOJUEGO

EXECUTE SP_VIDEOJUEGO_INSERT 'F001','El señor de los anillos','2002-10-05','S',10,'TCN','D'

EXECUTE SP_VIDEOJUEGO_INSERT 'F017','El señor de los anillos','2002-10-05','S',50,'TCN','D'
  
EXECUTE SP_VIDEOJUEGO_INSERT 'F017','El señor de los anillos','1990-01-01','S',10,'TCN','D'

EXECUTE SP_VIDEOJUEGO_INSERT 'F017','El señor de los anillos','2002-10-05','D',10,'TCN','D' 

EXECUTE SP_VIDEOJUEGO_INSERT 'F017','El señor de los anillos','2009-12-15','S',10,'TCN','A'

-- B

CREATE PROCEDURE SP_ELIMINAR_CLIENTE(@p_CODCLI INT)
AS
BEGIN
    IF EXISTS (SELECT * FROM T3FL_PRESTAMO WHERE CODCLI = @p_CODCLI)
		BEGIN
		    DELETE FROM T3FL_PRESTAMO WHERE CODCLI = @p_CODCLI
		    PRINT 'Se eliminaron los préstamos asociados al cliente.'
		END
    ELSE
		BEGIN
		    PRINT 'El cliente no tiene préstamos asociados.'
		END

    DELETE FROM T3FL_CLIENTE WHERE CODCLI = @p_CODCLI;
    PRINT 'Se eliminó el cliente con éxito.';
END

INSERT INTO T3FL_PRESTAMO VALUES ('F001', 100, '2024-07-03', '2024-07-04')
SELECT * FROM T3FL_PRESTAMO

EXECUTE SP_ELIMINAR_CLIENTE 100

EXECUTE SP_ELIMINAR_CLIENTE 103

SELECT * FROM T3FL_PRESTAMO


-- PREGUNTA 2
-- A
SELECT * FROM T3FL_PRESTAMO
SELECT * FROM T3FL_VIDEOJUEGO
SELECT * FROM T3FL_CLIENTE

INSERT INTO T3FL_PRESTAMO VALUES ('F001', 101, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F001', 101, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F001', 101, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F001', 101, '2024-07-03', '2024-07-04')

INSERT INTO T3FL_PRESTAMO VALUES ('F002', 102, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F002', 102, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F002', 102, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F002', 102, '2024-07-03', '2024-07-04')
																	   
INSERT INTO T3FL_PRESTAMO VALUES ('F003', 104, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F003', 104, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F003', 104, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F003', 104, '2024-07-03', '2024-07-04')
														 			   
INSERT INTO T3FL_PRESTAMO VALUES ('F004', 105, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F004', 105, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F004', 105, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F004', 105, '2024-07-03', '2024-07-04')
														 			   
INSERT INTO T3FL_PRESTAMO VALUES ('F005', 106, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F005', 106, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F005', 106, '2024-07-03', '2024-07-04')
INSERT INTO T3FL_PRESTAMO VALUES ('F005', 106, '2024-07-03', '2024-07-04')

SELECT * FROM T3FL_PRESTAMO


-- B
DECLARE C_Videojuego CURSOR FOR
SELECT v.CODVJG, f.CODFAB FROM T3FL_VIDEOJUEGO v 
	INNER JOIN T3FL_FABRICANTE f ON v.CODFAB = f.CODFAB
DECLARE @v_CODVJG char(5),
		@v_CODFAB char(3)

OPEN C_Videojuego
FETCH NEXT FROM C_Videojuego INTO @v_CODVJG, @v_CODFAB
WHILE (@@FETCH_STATUS = 0)
	BEGIN
		PRINT 'Videojuego: ' + @v_CODVJG + ' - Fabricante: ' + @v_CODFAB 
		PRINT 'Préstamos:'
		------------------------------------------------------------------
		DECLARE C_Cliente CURSOR FOR
		SELECT p.CODCLI, p.FECINIPRS, p.FECFINPRS 
	    FROM T3FL_PRESTAMO p
	    INNER JOIN T3FL_CLIENTE c ON p.CODCLI = c.CODCLI
	    WHERE p.CODVJG = @v_CODVJG AND c.ESTCLI = 'A'
		
		DECLARE @v_CODCLI int, @v_FECINIPRS datetime, @v_FECFINPRS datetime
		DECLARE @INDICE int = 0, @PRECIO_ACUM int = 0
		DECLARE @v_DIAS int
		
		OPEN C_Cliente
		FETCH NEXT FROM C_Cliente INTO @v_CODCLI, @v_FECINIPRS, @v_FECFINPRS
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			SET @INDICE = @INDICE + 1
			SET @v_DIAS = DATEDIFF(day, @v_FECINIPRS, @v_FECFINPRS)
			PRINT '#' + CAST(@INDICE AS VARCHAR) + ' - Cliente ' + CAST(@v_CODCLI AS VARCHAR) + 
				' - Desde: ' + CAST(@v_FECINIPRS AS VARCHAR) + ' - Hasta: ' + CAST(@v_FECFINPRS AS VARCHAR) + ' - ' + CAST(@v_DIAS AS VARCHAR) + ' día(s)'
			SET @PRECIO_ACUM = @PRECIO_ACUM + 5
			FETCH NEXT FROM C_Cliente INTO @v_CODCLI, @v_FECINIPRS, @v_FECFINPRS
		END
		CLOSE C_Cliente
		DEALLOCATE C_Cliente
		PRINT 'Total facturado: S/.' + CAST(@PRECIO_ACUM AS VARCHAR)
		PRINT ''
		------------------------------------------------------------------
		FETCH NEXT FROM C_Videojuego INTO @v_CODVJG, @v_CODFAB
	END
CLOSE C_Videojuego
DEALLOCATE C_Videojuego


-- PREGUNTA 3

CREATE TABLE TB_AUDITORIA
(
ID INT PRIMARY KEY IDENTITY(1,1),
FECHA_HORA_TRANS DATETIME DEFAULT GETDATE(),
TIPO_TRANS VARCHAR(20),
LOGIN_TRANS VARCHAR(100),
NUM_PRES INT,
COLUMNA NVARCHAR(20),
NUEVO_VALOR NVARCHAR(100)
)

CREATE TRIGGER TRG_AUDITORIA_PRESTAMO
ON T3FL_PRESTAMO
AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON;

	IF (DATEPART(dw, GETDATE()) IN (3, 4) AND DATEPART(HOUR, GETDATE()) BETWEEN 10 AND 17)
		BEGIN
			DECLARE @v_TIPO_TRANS VARCHAR(50)
			SET @v_TIPO_TRANS = 'UPDATE'

			DECLARE @v_LOGIN_TRANS VARCHAR(100)
			SET @v_LOGIN_TRANS = SYSTEM_USER

			INSERT INTO TB_AUDITORIA (TIPO_TRANS, LOGIN_TRANS, NUM_PRES, COLUMNA, NUEVO_VALOR)
			SELECT @v_TIPO_TRANS, @v_LOGIN_TRANS, i.COD_PRS, 'FECINIPRS', CONVERT(VARCHAR(100), d.FECINIPRS)
			FROM inserted i
			JOIN deleted d ON i.COD_PRS = d.COD_PRS
			WHERE i.FECINIPRS <> d.FECINIPRS

			INSERT INTO TB_AUDITORIA (TIPO_TRANS, LOGIN_TRANS, NUM_PRES, COLUMNA, NUEVO_VALOR)
			SELECT @v_TIPO_TRANS, @v_LOGIN_TRANS, i.COD_PRS, 'FECFINPRS', CONVERT(VARCHAR(100), d.FECFINPRS)
			FROM inserted i
			JOIN deleted d ON i.COD_PRS = d.COD_PRS
			WHERE i.FECFINPRS <> d.FECFINPRS
		END
	ELSE
		PRINT 'ERROR: Solo se puede actualizar datos de la tabla T3FL_PRESTAMO en'
		PRINT 'las columnas FECINIPRS o FECFINPRS los Martes y los Miércoles entre' 
		PRINT 'las 10:00 horas y las 17:00 horas.'
END



select * from TB_AUDITORIA

INSERT INTO T3FL_PRESTAMO VALUES ('F001',101,GETDATE(),'2024-07-06')

UPDATE T3FL_PRESTAMO SET FECFINPRS='2024-07-08'WHERE COD_PRS=201

DELETE FROM T3FL_PRESTAMO WHERE COD_PRS=221

select * from TB_AUDITORIA


-- PREGUNTA 4
-- A

ALTER TABLE T3FL_VIDEOJUEGO ADD NUM_PRES INT DEFAULT 0
UPDATE T3FL_VIDEOJUEGO SET NUM_PRES = DEFAULT WHERE NUM_PRES IS NULL
SELECT * FROM T3FL_VIDEOJUEGO


-- B

CREATE TRIGGER TRG_ACTUALIZAR_VIDEOJUEGO
ON T3FL_PRESTAMO
AFTER INSERT, DELETE
AS
BEGIN
    SET NOCOUNT ON

    DECLARE @v_CODVJG char(5)
    DECLARE @v_NUM_PRES_ACTUAL int
    DECLARE @NUEVO_STATUS char(1)

    IF EXISTS (SELECT * FROM inserted)
		BEGIN
		    SELECT @v_CODVJG = v.CODVJG
		    FROM T3FL_VIDEOJUEGO v
		    INNER JOIN inserted i ON v.CODVJG = i.CODVJG

		    SELECT @v_NUM_PRES_ACTUAL = NUM_PRES
		    FROM T3FL_VIDEOJUEGO
		    WHERE CODVJG = @v_CODVJG

		    UPDATE T3FL_VIDEOJUEGO
		    SET NUM_PRES = @v_NUM_PRES_ACTUAL + 1, STATUS = 'R'
		    WHERE CODVJG = @v_CODVJG
		END

    IF EXISTS (SELECT * FROM deleted)
		BEGIN
		    SELECT @v_CODVJG = v.CODVJG
		    FROM T3FL_VIDEOJUEGO v
		    INNER JOIN deleted d ON v.CODVJG = d.CODVJG

		    SELECT @v_NUM_PRES_ACTUAL = NUM_PRES
		    FROM T3FL_VIDEOJUEGO
		    WHERE CODVJG = @v_CODVJG

		    IF @v_NUM_PRES_ACTUAL > 1
		        SET @NUEVO_STATUS = 'R'
		    ELSE
		        SET @NUEVO_STATUS = 'D'
		    UPDATE T3FL_VIDEOJUEGO SET NUM_PRES = @v_NUM_PRES_ACTUAL - 1, STATUS = @NUEVO_STATUS
		    WHERE CODVJG = @v_CODVJG
		END
END


-- C

SELECT * FROM T3FL_VIDEOJUEGO

INSERT INTO T3FL_PRESTAMO VALUES ('F001', 101, '2024-07-01', '2024-07-02')
INSERT INTO T3FL_PRESTAMO VALUES ('F003', 102, '2024-07-01', '2024-07-02')
INSERT INTO T3FL_PRESTAMO VALUES ('F005', 108, '2024-07-01', '2024-07-02')

SELECT * FROM T3FL_VIDEOJUEGO

-- D

SELECT * FROM T3FL_VIDEOJUEGO

DELETE FROM T3FL_PRESTAMO WHERE CODVJG='F001'
DELETE FROM T3FL_PRESTAMO WHERE CODVJG='F003'
DELETE FROM T3FL_PRESTAMO WHERE CODVJG='F005'

SELECT * FROM T3FL_VIDEOJUEGO


-- PREGUNTA 5

CREATE TABLE T_TABLAFINAL_T3FL
(
MINOMBRE	VARCHAR(100),
MIHORARIO	DATETIME
)

INSERT INTO T_TABLAFINAL_T3FL VALUES ('Raúl Ichiro Rosas Chinen', GETDATE())

SELECT * FROM T_TABLAFINAL_T3FL