CREATE DATABASE BDT1T3FL_G2_RRC1
ON PRIMARY
(NAME=BDT1T3FL_G2_RRC1,
FILENAME='D:\AAA_Cibertec\3° CICLO\BDA 1\BDA1_examenT1_solucion\Solucion\BDT1T3FL.mdf')
LOG ON
(NAME=BDT1T3FL_G2_RRC1_LOG,
FILENAME='D:\AAA_Cibertec\3° CICLO\BDA 1\BDA1_examenT1_solucion\Solucion\BDT1T3FL_log.ldf')

SP_HELPDB BDT1T3FL_G2_RRC1

SP_WHO2

USE BDT1T3FL_G2_RRC1

CREATE SCHEMA simulacro

CREATE TABLE simulacro.T_VIDEOJUEGO
(
ID_VIDEOJUEGO	CHAR(4) PRIMARY KEY,
NOMBRE			VARCHAR(100)	NOT NULL UNIQUE,
MARCA			VARCHAR(50)		NOT NULL,
GENERO			VARCHAR(100)	NOT NULL,
CONSOLA			VARCHAR(50)		NOT NULL CHECK (CONSOLA IN ('NES','SNES','WII','WIIU','COMPUTER')),
ANNO_PUBLICA	INT				NOT NULL CHECK (ANNO_PUBLICA > 2000),
MULTIJUGADOR	CHAR(2)			NOT NULL DEFAULT 'NO' CHECK (MULTIJUGADOR IN ('SI','NO'))
)

CREATE TABLE simulacro.T_CLIENTE
(
ID_CLIENTE	INT	PRIMARY KEY,
NOMBRES		VARCHAR(20)	NOT NULL,
APELLIDOS	VARCHAR(10)	NOT NULL,
DNI			VARCHAR(8)	NOT NULL UNIQUE,
DISTRITO	VARCHAR(30)	NOT NULL
)

CREATE TABLE simulacro.T_PRESTAMOS
(
ID_ALQUILER			INT		PRIMARY KEY IDENTITY(1,1),
ID_VIDEOJUEGO		CHAR(4)	NOT NULL REFERENCES simulacro.T_VIDEOJUEGO(ID_VIDEOJUEGO),
FECHA_PRESTAMO		DATE	NOT NULL,
ID_CLIENTE			INT		NOT NULL REFERENCES simulacro.T_CLIENTE(ID_CLIENTE),
FECHA_DEVOLUCION	DATE	NOT NULL,
FECHA_DEVOLUCION_REAL	DATE	NULL
)

SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM SYS.TABLES
-- T_VIDEOJUEGO 901578250
-- T_CLIENTE	1013578649
-- T_PRESTAMOS	1109578991
SELECT * FROM sys.columns WHERE object_id=901578250
SELECT * FROM sys.columns WHERE object_id=1013578649
SELECT * FROM sys.columns WHERE object_id=1109578991

SELECT * FROM sys.key_constraints
SELECT * FROM sys.foreign_keys
SELECT * FROM sys.check_constraints
SELECT * FROM sys.default_constraints
SELECT * FROM sys.identity_columns

INSERT INTO simulacro.T_VIDEOJUEGO 
VALUES	(1,'Elden Ring','SONY','AVENTURA','COMPUTER',2023,'SI'),
		(2,'Juego de tronos','SONY','AVENTURA','WIIU',2020,'NO'),
		(3,'Rocket League','EPICGAMES','ARCADE','COMPUTER',2023,'SI'),
		(4,'Dead By Daylight','BEHAVIOUR','TERROR','COMPUTER',2016,'SI'),
		(5,'GTA San Andreas','ROCKSTAR','AVENTURA','COMPUTER',2004,'NO')

INSERT INTO simulacro.T_CLIENTE 
VALUES	(1,'JOSE','PEREZ','12345678','CHORRILLOS'),
		(2,'MAURICIO','RODRIGUEZ','23455678','MIRAFLORES'),
		(3,'JAVIER','MORALES','01234567','BARRANCO'),
		(4,'GABRIELA','LINARES','00123456','SAN BORJA'),
		(5,'NAYELI','POMPA','87654321','CHORRILLOS')


select * from simulacro.T_CLIENTE

INSERT INTO simulacro.T_PRESTAMOS
VALUES	('1',GETDATE(),1,GETDATE(),GETDATE())
GO 20

SELECT * FROM sys.identity_columns

SELECT * FROM simulacro.T_VIDEOJUEGO
SELECT * FROM simulacro.T_CLIENTE
SELECT * FROM simulacro.T_PRESTAMOS

--ANTES
SELECT* FROM simulacro.T_PRESTAMOS

--DESPUES 
SELECT DATEADD(DAY,3,FECHA_DEVOLUCION) FROM simulacro.T_PRESTAMOS

SELECT	P.ID_ALQUILER, C.ID_CLIENTE, C.NOMBRES, V.ID_VIDEOJUEGO, V.NOMBRE, V.MULTIJUGADOR
FROM	simulacro.T_PRESTAMOS P, simulacro.T_CLIENTE C, simulacro.T_VIDEOJUEGO V
WHERE	P.ID_VIDEOJUEGO = V.ID_VIDEOJUEGO AND P.ID_CLIENTE = C.ID_CLIENTE

SELECT simulacro.T_PRESTAMOS.ID_VIDEOJUEGO, simulacro.T_VIDEOJUEGO.NOMBRE, COUNT(simulacro.T_PRESTAMOS.ID_VIDEOJUEGO) AS 'CONTEO'
FROM simulacro.T_PRESTAMOS, simulacro.T_VIDEOJUEGO
WHERE simulacro.T_PRESTAMOS.ID_VIDEOJUEGO = simulacro.T_VIDEOJUEGO.ID_VIDEOJUEGO
GROUP BY simulacro.T_PRESTAMOS.ID_VIDEOJUEGO, simulacro.T_VIDEOJUEGO.NOMBRE

USE BDT1T3FL_G2_RRC1

CREATE SCHEMA inventario

CREATE SCHEMA logistica

SELECT * FROM sys.schemas

CREATE TABLE inventario.T_PRODUCTO
(
ID_PRD		INT				NOT NULL PRIMARY KEY IDENTITY(1000,10),
DESCR_PRD	VARCHAR(100)	NOT NULL UNIQUE,
CATEG_PRD	VARCHAR(50)		NOT NULL,
STK_ACTUAL	INT				NOT NULL CHECK(STK_ACTUAL>10),
STK_MINIMO	INT				NOT NULL CHECK(STK_MINIMO>10),
ESTADO		CHAR(1)			NOT NULL CHECK(ESTADO IN ('A','I','N')) DEFAULT 'A',
PAIS_ORIGEN	VARCHAR(50)		NOT NULL
)

CREATE TABLE inventario.T_LIBROS
(
ID_LIBRO		CHAR(4)			PRIMARY KEY,
TITULO			VARCHAR(100)	NOT NULL,
EDITORIAL		VARCHAR(100)	NOT NULL,
PRECIO			MONEY			NOT NULL CHECK(PRECIO BETWEEN 19.99 AND 299.99),
GENEROS			VARCHAR(100)	NOT NULL,
CANTIDAD		INT				NOT NULL,
CALIFICACION	INT				NOT NULL CHECK(CALIFICACION BETWEEN 0 AND 100)
)

SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM SYS.TABLES
-- T_PRODUCTO 1429580131
-- T_LIBROS	  1541580530
SELECT * FROM sys.columns WHERE object_id=1429580131
SELECT * FROM sys.columns WHERE object_id=1541580530

SELECT * FROM sys.key_constraints
SELECT * FROM sys.check_constraints
SELECT * FROM sys.default_constraints
SELECT * FROM sys.identity_columns

BULK INSERT inventario.T_PRODUCTO
FROM 'D:\AAA_Cibertec\3° CICLO\BDA 1\BDA1_examenT1_solucion\Solucion\bulk_para_T_PRODUCTO.csv'
WITH
(
FIELDTERMINATOR=',',
ROWTERMINATOR='\n'
)

BULK INSERT inventario.T_LIBROS
FROM 'D:\AAA_Cibertec\3° CICLO\BDA 1\BDA1_examenT1_solucion\Solucion\bulk_para_T_LIBROS.csv'
WITH
(
FIELDTERMINATOR=',',
ROWTERMINATOR='\n'
)

SELECT * FROM inventario.T_PRODUCTO
SELECT * FROM inventario.T_LIBROS

ALTER SCHEMA logistica TRANSFER inventario.T_PRODUCTO
ALTER SCHEMA logistica TRANSFER inventario.T_LIBROS

SELECT * FROM logistica.T_PRODUCTO
SELECT * FROM logistica.T_LIBROS