Equipo memoria 30GB

Instancia SQLServer 80% - 24gb

24576 MB
--------------

Inst1	8gb
Inst2	8gb
Inst3	4gb
Inst4	4gb
-----------
80% - 24gb


------------
BD
- mdf - master data file (tablas, data)
- ldf - log data file (insert, update, delete)
	
	
-------------
sp_helpdb 

sp_helpdb BD_COLEGIO

CREATE DATABASE NBD1;
SP_HELPDB NBD1;

CREATE DATABASE NBD2;
sp_helpdb NBD2;

CREATE DATABASE NBD3
ON PRIMARY
(NAME=NBD3,
FILENAME='D:\AAA_Cibertec\3° CICLO\BDA 1\sem1\NBD3.mdf')
LOG ON
(NAME=NBD3_LOG,
FILENAME='D:\AAA_Cibertec\3° CICLO\BDA 1\sem1\NBD3_LOG.ldf')

sp_helpdb NBD3

use NBD3

---------
DROP DATABASE NBD3

SP_WHO2

KILL 75
KILL 137

-------------------
CREATE TABLE TB_CLIENTE
(
codigo INT,
razon_social VARCHAR(100)
)

--DBO --> DATABASE OBJECT
--SCHEMA  X DEFAULT

CREATE SCHEMA ventas

CREATE TABLE ventas.TB_PRODUCTO
(
cod_prd INT,
descripcion VARCHAR(200)
)

SELECT * FROM sys.tables
--1205579333 TB_CLIENTE
SELECT * FROM sys.schemas
SELECT * FROM sys.columns WHERE object_id=1205579333

--56	INT
--167	VARCHAR
SELECT * FROM sys.types WHERE system_type_id=167

SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

DROP SCHEMA ventas

DROP TABLE ventas.TB_PRODUCTO

CREATE TABLE TB_PRODUCTO
(
numero INT,
nombre VARCHAR(20),
estado CHAR(1),
fecha DATE
)

SELECT * FROM TB_PRODUCTO
SELECT * FROM ventas.TB_PRODUCTO

DROP TABLE ventas.TB_PRODUCTO
DROP SCHEMA ventas





--------------------------------
-- CREATE DROP DATABASE
-- CREATE ALTER DROP TABLE
-- CONSTRAINTS --> para las columnas
-- UNIQUE
-- PRIMARY KEY
-- FOREIGN KEY
-- NULL / NOT NULL
-- CHECK
-- DEFAULT
-- IDENTITY

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE VALUES (100,'CLIENTE 100')

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE VALUES (NULL, NULL)

SELECT * FROM TB_CLIENTE

--ALTER TABLE TB_CLIENTE ALTER COLUMN CODIGO INT NOT NULL

UPDATE TB_CLIENTE SET codigo=200 WHERE codigo IS NULL

SELECT * FROM TB_CLIENTE

ALTER TABLE TB_CLIENTE ALTER COLUMN codigo INT NOT NULL

--ALTER TABLE TB_CLIENTE ALTER COLUMN RAZON_SOCIAL VARCHAR(100) NOT NULL

--VARCHAR(100)
--VARCHAR(50)
--COLUMNA = 90 caracteres

UPDATE TB_CLIENTE SET razon_social='CLIENTE 200' WHERE codigo=200
ALTER TABLE TB_CLIENTE ALTER COLUMN razon_social VARCHAR(100) NOT NULL

INSERT INTO TB_CLIENTE VALUES (100,'CLIENTE 100')

SELECT * FROM TB_CLIENTE

DELETE TB_CLIENTE WHERE CODIGO=100
INSERT INTO TB_CLIENTE VALUES (100,'CLIENTE 100')
SELECT * FROM TB_CLIENTE

ALTER TABLE TB_CLIENTE ADD PRIMARY KEY (codigo)

--INSERT INTO TB_CLIENTE VALUES (100,'CLIENTE 100')
INSERT INTO TB_CLIENTE VALUES (300,'CLIENTE 100')

SELECT * FROM TB_CLIENTE

UPDATE TB_CLIENTE SET razon_social='CLIENTE 300' WHERE codigo=300

SELECT * FROM TB_CLIENTE

ALTER TABLE TB_CLIENTE ADD CONSTRAINT UQ_TB_CLIENTE_RAZON_SOCIAL UNIQUE(razon_social)

--INSERT INTO TB_CLIENTE VALUES (400,'CLIENTE 100')
INSERT INTO TB_CLIENTE VALUES (400,'CLIENTE  100')

SELECT * FROM TB_CLIENTE

--ALTER TABLE TB_CLIENTE ADD estado CHAR(1) NOT NULL
ALTER TABLE TB_CLIENTE ADD estado CHAR(1)

SELECT * FROM TB_CLIENTE

UPDATE TB_CLIENTE SET estado='A' WHERE codigo IN (100,300)
UPDATE TB_CLIENTE SET estado='B' WHERE codigo=200 OR codigo=400

ALTER TABLE TB_CLIENTE ALTER COLUMN estado CHAR(1) NOT NULL

SELECT * FROM TB_CLIENTE

--INSERT INTO TB_CLIENTE VALUES (500,'CLIENTE 500',NULL)
INSERT INTO TB_CLIENTE VALUES (500,'CLIENTE 500','A')

ALTER TABLE TB_CLIENTE 
ADD tipo INT NOT NULL DEFAULT 1

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE VALUES (600,'CLIENTE 600','A',2)

--INSERT INTO TB_CLIENTE VALUES (600,'CLIENTE 600',DEFAULT, DEFAULT)

INSERT INTO TB_CLIENTE VALUES (700,'CLIENTE 700','B', DEFAULT)

SELECT * FROM TB_CLIENTE

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT CHK_TB_CLIENTE_ESTADO
CHECK (estado IN ('A','B','C')   )

--INSERT INTO TB_CLIENTE VALUES (800,'CLIENTE 800','X', DEFAULT)
INSERT INTO TB_CLIENTE VALUES (800,'CLIENTE 800','C', DEFAULT)

SELECT * FROM TB_CLIENTE

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CHK_TB_CLIENTE_TIPO CHECK (tipo=1 OR tipo=2 OR tipo=3)

--INSERT INTO TB_CLIENTE VALUES (900,'CLIENTE 900','C', 99)
INSERT INTO TB_CLIENTE VALUES (900,'CLIENTE 900','C',3)

SELECT * FROM TB_CLIENTE

--UPDATE TB_CLIENTE SET tipo=99
UPDATE TB_CLIENTE SET tipo=2

SELECT * FROM TB_CLIENTE

CREATE TABLE TB_FACTURA
(
num_fac INT PRIMARY KEY,
fec_fac DATE NOT NULL,
cod_cli INT NOT NULL REFERENCES TB_CLIENTE(codigo)
)

--INSERT INTO TB_FACTURA VALUES (1000, GETDATE(), 99 )
INSERT INTO TB_FACTURA VALUES (1000, GETDATE(), 900 )

SELECT * FROM TB_FACTURA

--INSERT INTO TB_FACTURA VALUES (1000, GETDATE(), 800 )
INSERT INTO TB_FACTURA VALUES (1010, GETDATE(), 800 )

INSERT INTO TB_FACTURA VALUES 
(1020, GETDATE(), 700 ),
(1030, GETDATE(), 700 ),
(1040, GETDATE(), 700 ),
(1050, GETDATE(), 700 ),
(1060, GETDATE(), 700 )

SELECT * FROM TB_FACTURA

INSERT INTO TB_FACTURA VALUES 
(1080, GETDATE(), 9 ),
(1090, GETDATE(), 600 ),
(1070, GETDATE(), 600 )

SELECT * FROM sys.tables
--TB_CLIENTE	1381579960
--TB_PRODUCTO	1413580074
SELECT * FROM sys.key_constraints WHERE parent_object_id=1381579960

SELECT * FROM sys.foreign_keys
SELECT * FROM sys.check_constraints
SELECT * FROM sys.default_constraints

SELECT * FROM sys.columns where object_id=1381579960

DROP TABLE TB_FACTURA

CREATE TABLE TB_FACTURA
(
num_fac INT PRIMARY KEY IDENTITY(500,2),
fec_fac DATE NOT NULL,
cod_cli INT NOT NULL REFERENCES TB_CLIENTE(codigo)
)

SELECT * FROM TB_FACTURA

--INSERT INTO TB_FACTURA VALUES (1010, GETDATE(), 800 )
INSERT INTO TB_FACTURA VALUES (GETDATE(), 800 )
SELECT * FROM TB_FACTURA

INSERT INTO TB_FACTURA VALUES (GETDATE(), 600 )

SELECT * FROM TB_FACTURA

INSERT INTO TB_FACTURA VALUES 
(GETDATE(), 100 ), (GETDATE(), 200 ),
(GETDATE(), 300 ), (GETDATE(), 400 )

SELECT * FROM TB_FACTURA

--INSERT INTO TB_FACTURA VALUES  (GETDATE(), 100 ), (GETDATE(), 9 )
INSERT INTO TB_FACTURA VALUES  (GETDATE(), 100 ), (GETDATE(), 900 )

SELECT * FROM TB_FACTURA

UPDATE TB_FACTURA SET num_fac=512 WHERE num_fac=516

SELECT * FROM sys.identity_columns

ALTER TABLE TB_PRODUCTO ALTER COLUMN numero INT NOT NULL

ALTER TABLE TB_PRODUCTO ADD PRIMARY KEY (numero)

CREATE TABLE TB_DETALLE_FACTURA
(
num_fac	INT REFERENCES TB_FACTURA(num_fac),
cod_prd INT REFERENCES TB_PRODUCTO(numero),
cant	INT  NOT NULL,
pre_unit MONEY NOT NULL
PRIMARY KEY (num_fac, cod_prd)
)

SELECT * FROM TB_FACTURA
SELECT * FROM TB_PRODUCTO

INSERT INTO TB_PRODUCTO VALUES
(10,'PRODUCTO 10','A','2020-05-05'),
(20,'PRODUCTO 20','A','2020-04-05'),
(30,'PRODUCTO 30','A','2020-03-05')

INSERT INTO TB_DETALLE_FACTURA VALUES (500, 10, 5000, 1.99)
--INSERT INTO TB_DETALLE_FACTURA VALUES (600, 10, 5000, 1.99)
--INSERT INTO TB_DETALLE_FACTURA VALUES (500, 10, 5000, 1.99)
INSERT INTO TB_DETALLE_FACTURA VALUES (500, 20, 9000, 2.99)

SELECT * FROM TB_DETALLE_FACTURA

	
	
	
	