USE MASTER 
GO
/* VALIDANDO LA EXISTENCIA DE LA BASE COMERCIO */ 
IF DB_ID('T3FL_COMERCIO') IS NOT NULL
DROP DATABASE T3FL_COMERCIO
GO
/* CREANDO LA BASE DE DATOS */
CREATE DATABASE T3FL_COMERCIO
GO
/* ACTIVANDO LA BASE DE DATOS */
USE T3FL_COMERCIO
GO
/* CREANDO LAS TABLAS */
CREATE TABLE TB_DISTRITO (
COD_DIS char (3) NOT NULL,
NOM_DIS varchar (50) NULL,
PRIMARY KEY (COD_DIS)
)
GO
CREATE TABLE TB_LINEA (
LIN_PRO int NOT NULL,
NOM_LIN varchar (30) NOT NULL,
PRIMARY KEY (LIN_PRO)
)
GO
CREATE TABLE TB_VENDEDOR (
COD_VEN char (3) NOT NULL,
NOM_VEN varchar (20) NOT NULL,
APE_VEN varchar (20) NOT NULL,
SUE_VEN money NOT NULL,
FEC_ING date NULL,
TIP_VEN int NOT NULL,
COD_DIS char (3) NOT NULL,
PRIMARY KEY (COD_VEN)
)
GO
CREATE TABLE TB_PROVEEDOR (
COD_PRV char (4) NOT NULL,
RAZ_SOC_PRV varchar (80) NOT NULL,
DIR_PRV varchar (100) NOT 
NULL,
TEL_PRV varchar (15) NULL,
COD_DIS char (3) NOT NULL,
REP_VEN varchar (80) NULL,
PRIMARY KEY (COD_PRV)
)
GO
CREATE TABLE TB_PRODUCTO (
COD_PRO char (4) NOT NULL,
DES_PRO varchar (50) NOT NULL,
PRE_PRO decimal (10, 2) NOT NULL,
STK_ACT int NOT NULL,
STK_MIN int NOT NULL,
UNI_MED varchar (30) NOT NULL,
LIN_PRO int NOT NULL,
IMPORTADO varchar (10) NOT NULL,
PRIMARY KEY (COD_PRO)
)
GO
CREATE TABLE TB_CLIENTE (
COD_CLI char (5) NOT NULL,
RAZ_SOC_CLI char (30) NOT NULL,
DIR_CLI varchar (100) NOT NULL,
TEL_CLI varchar (9) NOT NULL,
RUC_CLI varchar (15) NULL,
COD_DIS char (3) NOT NULL,
FEC_REG date NULL,
TIP_CLI int NULL,
CONTACTO varchar (30) NULL,
PRIMARY KEY (COD_CLI)
)
GO
CREATE TABLE TB_ABASTECIMIENTO (
COD_PRV char (4) NOT NULL,
COD_PRO char (4) NOT NULL,
PRE_ABA decimal (7, 2) NULL
PRIMARY KEY (COD_PRV, COD_PRO)
)
GO
CREATE TABLE TB_ORDEN_COMPRA (
NUM_OCO varchar (5) NOT NULL,
FEC_OCO date NULL,
COD_PRV char (4) NOT NULL,
FEC_ATE date NULL,
EST_OCO int NOT NULL,
PRIMARY KEY (NUM_OCO)
)
GO
CREATE TABLE TB_FACTURA (
NUM_FAC int NOT NULL IDENTITY (100,1),
FEC_FAC date NULL,
COD_CLI char (5) NOT NULL,
FEC_CAN date NULL,
EST_FAC int NOT NULL,
COD_VEN char (3) NOT NULL,
POR_IGV decimal (4,2) NULL,
PRIMARY KEY (NUM_FAC)
)
GO
CREATE TABLE TB_DETALLE_FACTURA (
NUM_FAC int NOT NULL,
COD_PRO char (4) NOT NULL,
CAN_VEN int NOT NULL,
PRE_VEN money NOT NULL
PRIMARY KEY (NUM_FAC, COD_PRO)
)
GO
CREATE TABLE TB_DETALLE_COMPRA (
NUM_OCO varchar (5) NOT NULL,
COD_PRO char (4) NOT NULL,
CAN_PED int NOT NULL
)
GO
/* LLAVES FORANEAS */
ALTER TABLE TB_ABASTECIMIENTO
ADD FOREIGN KEY(COD_PRV) REFERENCES TB_PROVEEDOR (COD_PRV)
GO
ALTER TABLE TB_ABASTECIMIENTO
ADD FOREIGN KEY(COD_PRO) REFERENCES TB_PRODUCTO (COD_PRO)
GO
ALTER TABLE TB_CLIENTE
ADD FOREIGN KEY(COD_DIS) REFERENCES TB_DISTRITO (COD_DIS)
GO
ALTER TABLE TB_DETALLE_COMPRA
ADD FOREIGN KEY(COD_PRO) REFERENCES TB_PRODUCTO (COD_PRO)
GO
ALTER TABLE TB_DETALLE_COMPRA
ADD FOREIGN KEY(NUM_OCO) REFERENCES TB_ORDEN_COMPRA (NUM_OCO)
GO
ALTER TABLE TB_DETALLE_FACTURA
ADD FOREIGN KEY(COD_PRO) REFERENCES TB_PRODUCTO (COD_PRO)
GO
ALTER TABLE TB_DETALLE_FACTURA
ADD FOREIGN KEY(NUM_FAC) REFERENCES TB_FACTURA (NUM_FAC)
GO
ALTER TABLE TB_FACTURA
ADD FOREIGN KEY(COD_CLI) REFERENCES TB_CLIENTE (COD_CLI)
GO
ALTER TABLE TB_FACTURA
ADD FOREIGN KEY(COD_VEN) REFERENCES TB_VENDEDOR (COD_VEN)
GO
ALTER TABLE TB_ORDEN_COMPRA
ADD FOREIGN KEY(COD_PRV) REFERENCES TB_PROVEEDOR (COD_PRV)
GO
ALTER TABLE TB_PRODUCTO
ADD FOREIGN KEY(LIN_PRO) REFERENCES TB_LINEA (LIN_PRO)
GO
ALTER TABLE TB_PROVEEDOR
ADD FOREIGN KEY(COD_DIS) REFERENCES TB_DISTRITO (COD_DIS)
GO
ALTER TABLE TB_VENDEDOR
ADD FOREIGN KEY(COD_DIS) REFERENCES TB_DISTRITO (COD_DIS)
GO

sp_helpdb T3FL_COMERCIO